
GET http://localhost:8000/ok/


        //orders 
###
GET http://localhost:8000/orders


###
POST http://localhost:8000/orders
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJIZW5yeUBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgyODg5Nzl9.9aNbQtO6opDbQLkKoE4SvTr0_-FKjsTJ33OWVqNMSNY
Content-Type: application/json

{
  
  "price": 70,
  "discount": 0,
  "final_price": 70,
  "comment": "Add crips",
  "restaurant_id" : 10,
  "delivery_address_id": 19,
  "user_id" : 6,
  "driver_id": 3
}

###
DELETE http://localhost:8000/orders/29




                                   // state


###
GET http://localhost:8000/state


###

POST http://localhost:8000/state
Content-Type: application/json

{
   
    "name": "Florida",
    "code": "51"
}


###
DELETE http://localhost:8000/state/8

###

GET http://localhost:8000/city
###
GET http://localhost:8000/category
###
GET http://localhost:8000/comment
###
GET http://localhost:8000/driver/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJrYXJlbkBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImV4cCI6MTcxODA5ODg5NH0.t4OirTtHehbkGDO-PM3_VfVH8b-HHhHP5Tj-qWT0jdE
###
GET http://localhost:8000/menuItem
###
GET http://localhost:8000/orderMenuItem
###
GET http://localhost:8000/orderStatus
###
GET http://localhost:8000/statusCatalog
###
GET http://localhost:8000/address
###
GET http://localhost:8000/restaurantOwner
###
GET http://localhost:8000/restaurant
###
GET http://localhost:8000/users
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJIZW5yeUBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgyOTEwNTJ9.NAFuOaoDNsqg0N0s2UcG6qRrVDiXA3om7xfIeEDhabw

###
GET http://localhost:8000/users
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJIZW5yeUBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgyOTEwNTJ9.NAFuOaoDNsqg0N0s2UcG6qRrVDiXA3om7xfIeEDhabw

###

###
POST http://localhost:8000/orders
Content-Type: application/json

{
  
  "price": 120,
  "discount": 20,
  "final_price": 100,
  "comment": "Add sauce",
  "restaurant_id" : 10,
  "delivery_address_id": 19,
  "user_id" : 6,
  "driver_id": 3
}
###
POST http://localhost:8000/menuItem
Content-Type: application/json

{
  
   "name":"ricemix",
   " description": "ndengu beans",
   " ingredients":"rice,beans,ndengu",
    "price":80,
   " active":true,
    "created_at":"2023-6-8",
   " updated_at":"2023-6-9",
    "restaurant_id":10,
   "category_id":6
}


###

POST http://localhost:8000/restaurantOwner
Content-Type: application/json

{
   
    "owner_id": 6,
    "restaurant_id": 10
}
###
POST http://localhost:8000/state
Content-Type: application/json

{
   
    "name": "Detroit",
    "code": "41"
}

###

POST http://localhost:8000/orderStatus
Content-Type: application/json

{
  
    "order_id": 10,
    "status_catalog_id":2,
    "created_at":"2024-05-07"
   
}

###

POST http://localhost:8000/comment
Content-Type: application/json

{
    "comment_text":"Great",
    "is_complaint": false,
    "is_praise": true,
    "created_at":"2023-5-4",
    "updated_at":"2024-1-23",
    "order_id": 2,
    "user_id": 5
}
###

POST http://localhost:8000/category
Content-Type: application/json

{
   
    "name": "legumes"
}

###
POST http://localhost:8000/orderMenuItem
Content-Type: application/json

{
   
   " quantity": 2,
    "item_price": 450,
    "price":900,
   "order_id": 10,
    "menu_item_id":13
}
###
POST http://localhost:8000/address
Content-Type: application/json

{
   
    " street_address_1":" 987",
    "street_address_2": "9j6",
   " zip_code":"gh67",
   " delivery_instructions": "Three",
    "created_at":"2023-3-4",
   " updated_at":"2023-5-6",
    "user_id":5,
    "city_id": 3
}

###
POST http://localhost:8000/register
Content-Type: application/json

{
     "userId":6,
     "email":"Aina@gmail.com",
    "password":"pass"
}

###
POST http://localhost:8000/login
Content-Type: application/json

{
    "email":"Aina@gmail.com",
    "password":"pass"
}

###
POST http://localhost:8000/register
Content-Type: application/json

{
   
    "userId": 6,
    "email": "Mocca@gmail.com",
    "password": "783",
    "role": "user"
}


###
POST http://localhost:8000/register
Content-Type: application/json

{
   
    "userId": 6,
    "email": "Jazz@gmail.com",
    "password": "767",
    "role": "admin"
}

###
POST http://localhost:8000/login
Content-Type: application/json

{

    
    "email":"Jazz@gmail.com",
    "password":"767"
}


###
POST http://localhost:8000/register
Content-Type: application/json

{
   
    "userId": 8,
    "email": "Moore@gmail.com",
    "password": "767",
    "role": "admin"
}

###
POST http://localhost:8000/login
Content-Type: application/json

{
    "email":"Moore@gmail.com",
    "password":"767"
}

###
GET http://localhost:8000/state-with-cities


////               //////


###
GET http://localhost:8000/users
Authorization: eyJhbGcizI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJIZW5yeUBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgyODcxODR9.r4hlMbh-2t4ZV_lp9PIf3WAa22R2PKCMZdg2Agv_J-o


###
POST http://localhost:8000/register
Content-Type: application/json

{
   
    "userId": 8,
    "email": "Henry@gmail.com",
    "password": "767",
    "role": "admin"
 }

###
POST http://localhost:8000/login
Content-Type: application/json

{
    "email":"Henry@gmail.com",
    "password":"767"
}


// states table

###
GET http://localhost:8000/state
//uthorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJIZW5yeUBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgyOTEzODd9.3hT6uaRrqwyZKr3PP5gjuh7ZC0YuYgaVik-SMiFLbZI

###
POST http://localhost:8000/state
//Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJIZW5yeUBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgyOTE1OTJ9.PEiPefEKH_Qj4DTCUSNp6CrIegaDxxYuaxWAQbLD-cg
Content-Type: application/json

{
    "name": "Texas",
    "code": "597"
}


###
DELETE http://localhost:8000/state/14
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJIZW5yeUBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgyOTIyMTd9.kAUM67BbgzIuODqGCrZAdXnDgWpEhgtVoqXJ0-D9jtM
