
GET http://localhost:8000/ok/

###
GET http://localhost:8000/orders
###
GET http://localhost:8000/state
###

GET http://localhost:8000/city
###
GET http://localhost:8000/category
###
GET http://localhost:8000/comment
###
GET http://localhost:8000/driver/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJrYXJlbkBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImV4cCI6MTcxODA5ODg5NH0.t4OirTtHehbkGDO-PM3_VfVH8b-HHhHP5Tj-qWT0jdE
###
GET http://localhost:8000/menuItem
###
GET http://localhost:8000/orderMenuItem
###
GET http://localhost:8000/orderStatus
###
GET http://localhost:8000/statusCatalog
###
GET http://localhost:8000/address
###
GET http://localhost:8000/restaurantOwner
###
GET http://localhost:8000/restaurant
###
GET http://localhost:8000/users
Authorization:.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBaW5hQGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiZXhwIjoxNzE4MTM0NDkxfQ.AACBH5VM5AHW7d6LZ8nxF9bwng-agqGx_bI8BzxA-DU
###
GET http://localhost:8000/users
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJNb29yZUBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgyMDQ5NDd9.2CyrP6P5RKkVTGnWT2Ao8xSNanMqVO_10c7zIaYDKhY
###
POST  http://localhost:8000/users

{
 "name": "Bukayomi ",
    "contact_phone": "078954267",
    "phone_verified":true,
    "email":"bukayo@gmail.com",
    "email_verified":false,
    "confirmation_code":"ikg6",
    "password":"pass",
    "address": "Kutus, Kenya"
}

//orders delete
###
DELETE http://localhost:8000/orders/29
###
POST http://localhost:8000/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJNb29yZUBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgyMTE1MDN9.2bsq8pc8T6kbxxhuXZNG0CnH3zbMsUvmJmGPMEiNRy8
Content-Type: application/json

{
   
    "name": "Bukayomi ",
    "contact_phone": "078954267",
    "phone_verified":true,
    "email":"bukayo@gmail.com",
    "email_verified":false,
    "confirmation_code":"ikg6",
    "password":"pass",
    "address": "Kutus, Kenya"
}


###
POST http://localhost:8000/orders
Content-Type: application/json

{
  
  "price": 70,
  "discount": 0,
  "final_price": 70,
  "comment": "Add crips",
  "restaurant_id" : 10,
  "delivery_address_id": 19,
  "user_id" : 6,
  "driver_id": 3
}

###
POST http://localhost:8000/orders
Content-Type: application/json

{
  
  "price": 120,
  "discount": 20,
  "final_price": 100,
  "comment": "Add sauce",
  "restaurant_id" : 10,
  "delivery_address_id": 19,
  "user_id" : 6,
  "driver_id": 3
}
###
POST http://localhost:8000/menuItem
Content-Type: application/json

{
  
   "name":"ricemix",
   " description": "ndengu beans",
   " ingredients":"rice,beans,ndengu",
    "price":80,
   " active":true,
    "created_at":"2023-6-8",
   " updated_at":"2023-6-9",
    "restaurant_id":10,
   "category_id":6
}


###

POST http://localhost:8000/restaurantOwner
Content-Type: application/json

{
   
    "owner_id": 6,
    "restaurant_id": 10
}
###

POST http://localhost:8000/state
Content-Type: application/json

{
   
    "name": "Florida",
    "code": "51"
}
###
POST http://localhost:8000/state
Content-Type: application/json

{
   
    "name": "Detroit",
    "code": "41"
}

###

POST http://localhost:8000/orderStatus
Content-Type: application/json

{
  
    "order_id": 10,
    "status_catalog_id":2,
    "created_at":"2024-05-07"
   
}

###

POST http://localhost:8000/comment
Content-Type: application/json

{
    "comment_text":"Great",
    "is_complaint": false,
    "is_praise": true,
    "created_at":"2023-5-4",
    "updated_at":"2024-1-23",
    "order_id": 2,
    "user_id": 5
}
###

POST http://localhost:8000/category
Content-Type: application/json

{
   
    "name": "legumes"
}

###
POST http://localhost:8000/orderMenuItem
Content-Type: application/json

{
   
   " quantity": 2,
    "item_price": 450,
    "price":900,
   "order_id": 10,
    "menu_item_id":13
}
###
POST http://localhost:8000/address
Content-Type: application/json

{
   
    " street_address_1":" 987",
    "street_address_2": "9j6",
   " zip_code":"gh67",
   " delivery_instructions": "Three",
    "created_at":"2023-3-4",
   " updated_at":"2023-5-6",
    "user_id":5,
    "city_id": 3
}

###
POST http://localhost:8000/register
Content-Type: application/json

{
     "userId":6,
     "email":"Aina@gmail.com",
    "password":"pass"
}

###
POST http://localhost:8000/login
Content-Type: application/json

{
    "email":"Aina@gmail.com",
    "password":"pass"
}

###
POST http://localhost:8000/register
Content-Type: application/json

{
   
    "userId": 6,
    "email": "Mocca@gmail.com",
    "password": "783",
    "role": "user"
}


###
POST http://localhost:8000/register
Content-Type: application/json

{
   
    "userId": 6,
    "email": "Jazz@gmail.com",
    "password": "767",
    "role": "admin"
}

###
POST http://localhost:8000/login
Content-Type: application/json




###
POST http://localhost:8000/register
Content-Type: application/json

{
   
    "userId": 8,
    "email": "Moore@gmail.com",
    "password": "767",
    "role": "admin"
}

###
POST http://localhost:8000/login
Content-Type: application/json

{
    "email":"Moore@gmail.com",
    "password":"767"
}

###
GET http://localhost:8000/state-with-cities